Feature/init files
maosan132/my-weather-app pull request #1
Opened 2021-03-14 04:05 UTC by maosan132

# Description

Hello pals, I am re-submitting this pull request so everybody can give support and suggestions for making this project better, so it can be approved. Any suggestions will be fully appreciated. 

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-03-14 05:12 UTC, trekab reviewed
#### Invalid! :stop_sign: 
Hi @maosan132! Unfortunately, I have to invalidate your code review request because your current linter configuration won't run the linter checks as expected. Please redo your [linter configuration](https://github.com/microverseinc/linters-config/tree/master/javascript) and make sure that the necessary checks run on your pull request. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/) and [Zendesk](https://microverse.zendesk.com/hc/en-us/articles/1500002085202-February-2nd-2021-linter-errors-as-a-reason-of-project-invalidation-))

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

2021-03-21 09:41 UTC, BrittanyBlake commented
### Status: Invalid 🛑 
****
Hi @maosan132. This pull request has been marked as invalid because the linters are not configured correctly. Please take a look at how to set up the [linters config](https://github.com/microverseinc/linters-config/tree/master/javascript) and make the necessary changes.  


- It appears as though your project is missing the `.github` folder. Your linter config file should be in the`.github/workflows` folder.

- Also, please ensure that you have a descriptive `README` file before you submit your next pull request. It is missing a screenshot, the live demo link, and instructions on how to set up and run the project. 

****
Please make the required adjustments and submit a new code review request.

### Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2021-03-23 04:47 UTC, rindrajosia requested changes
Invalid :red_circle: 

- [ ]  This pull request will be marked as invalid in your project because GitHub Actions must be activated.
- [ ] It will be nice if you add screenshot in your readme as it is the first thing that users check.

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

2021-03-23 17:10 UTC, MuriloRoque requested changes
## Status: Changes requested :red_circle: 

### Hello @maosan132 :wave: 

### Amazing on this project, your page is doing what it's supposed to do and it's truly beautiful, including the images you chose for each weather! Also, I really liked the way you structured your app, properly separating every file, congratulations! There's only one issue we need to solve before moving on, alright? Please check my comment in your code below :smile: 

Kindly make the requested changes and submit them for another review, please :pray: 

I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2021-03-23 17:10 UTC, MuriloRoque commented on src/fetch-data.js
> +  const unit = 'metric';
- [ ] You need to add an option to either make the calls on Fahrenheit or Celsius depending on the user's preferences or build a toggle button to switch between the two of them after getting the result ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/search_requirement.png)).

2021-03-24 14:33 UTC, MuriloRoque approved these changes
## Status: Approved :green_circle: 

### Hello again @maosan132 :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2021-03-26 21:41 UTC, merged